# Generated by Django 3.2.7 on 2021-09-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cisco_output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cisco_output', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='device_creds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddressCredentials', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='hostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=25, unique=True)),
                ('hostname', models.CharField(max_length=25)),
                ('secret', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('deviceLocation', models.CharField(max_length=25)),
                ('deviceType', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ipaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ipAddressAndHostname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_Address', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ipWithDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=25, unique=True)),
                ('secret', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('deviceLocation', models.CharField(max_length=25)),
                ('deviceType', models.CharField(max_length=25)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipaddress', to='ztest_ztest1.ipaddressandhostname')),
            ],
        ),
    ]
