# Generated by Django 3.2.7 on 2021-09-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='ipaddress',
            new_name='ip_address',
        ),
    ]
