# Generated by Django 3.2.7 on 2021-09-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0002_rename_ipaddress_ipaddress_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdetails',
            name='vendorName',
            field=models.CharField(default='cisco', max_length=25),
        ),
    ]
