# Generated by Django 3.2.7 on 2021-09-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0004_remove_hostdetails_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdetails',
            name='secret',
            field=models.CharField(default='G0t2BTuf', max_length=25),
        ),
    ]
