# Generated by Django 3.2.7 on 2021-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0005_hostdetails_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cisco_output',
            old_name='cisco_output',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='hostdetails',
            name='secret',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='hostdetails',
            name='vendorName',
            field=models.CharField(max_length=25),
        ),
    ]
