# Generated by Django 3.2.7 on 2021-10-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0006_auto_20210930_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='cisco_output',
            name='timestamp',
            field=models.CharField(default='20', max_length=25),
        ),
    ]
