# Generated by Django 3.2.7 on 2021-10-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0007_cisco_output_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='timestamp',
            field=models.CharField(default=1633165928.2858539, max_length=30),
        ),
    ]
