# Generated by Django 3.2.7 on 2021-10-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0008_ipaddress_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cisco_output',
            name='success',
            field=models.CharField(default='True', max_length=10),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='timestamp',
            field=models.CharField(default=1633171762.981379, max_length=30),
        ),
    ]
