# Generated by Django 3.1 on 2022-02-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0009_auto_20211002_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciscoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(default=1643960988.398113, max_length=30)),
                ('payload', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='cisco_output',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device_creds',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hostdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hostdetails',
            name='ipaddress',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='timestamp',
            field=models.CharField(default=1643960988.3961146, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipaddressandhostname',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipwithdetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipwithdetail',
            name='ipaddress',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
