# Generated by Django 3.1 on 2022-02-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0010_auto_20220204_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciscoconfig',
            name='success',
            field=models.CharField(default='True', max_length=10),
        ),
        migrations.AlterField(
            model_name='ciscoconfig',
            name='timestamp',
            field=models.CharField(default=1643976092.4151824, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='timestamp',
            field=models.CharField(default=1643976092.4141848, max_length=30),
        ),
    ]
