# Generated by Django 3.1 on 2022-02-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0011_auto_20220204_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='cisco_config_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('timestamp', models.CharField(default='20', max_length=25)),
                ('success', models.CharField(default='True', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='ciscoconfig',
            name='timestamp',
            field=models.CharField(default=1644246679.1552885, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='timestamp',
            field=models.CharField(default=1644246679.1533048, max_length=30),
        ),
    ]
