# Generated by Django 3.1 on 2022-02-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0012_auto_20220207_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciscoconfig',
            name='timestamp',
            field=models.CharField(default=1644642153.2499588, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='timestamp',
            field=models.CharField(default=1644642153.247964, max_length=30),
        ),
    ]
