# Generated by Django 5.0.2 on 2024-02-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0015_alter_cisco_config_result_id_alter_cisco_output_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciscoconfig',
            name='timestamp',
            field=models.CharField(default=1708092323.3264427, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='timestamp',
            field=models.CharField(default=1708092323.3264427, max_length=30),
        ),
    ]
